# Creates a new tag, whenever the app version (in package.json) is updated in master
# And marks any relevant issues as fixed
name: 🏷️ Tag new Versions
on:
  push:
    branches:
      - master
jobs:
  tag-pre-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.autotag.outputs.tagname }}
    steps:
      - uses: actions/checkout@v4
      - uses: butlerlogic/action-autotag@stable
        id: autotag
        with:
          GITHUB_TOKEN: ${{ secrets.ORG_REPO_TOKEN || secrets.GITHUB_TOKEN }}
          strategy: package
          commit_message_template: "🔖 {{number}} {{message}} (by {{author}})\nSHA: {{sha}}\n."
  github-release:
    runs-on: ubuntu-latest
    needs: tag-pre-release
    if: ${{ needs.tag-pre-release.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ORG_REPO_TOKEN || secrets.GITHUB_TOKEN }}
          tag: ${{ needs.tag-pre-release.outputs.tag }}
          bodyFile: '.github/CHANGELOG.md'
  mark-issue-fixed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Label Fixed Issues
        uses: gh-bot/fix-labeler@master
        with:
          token: ${{ secrets.ORG_REPO_TOKEN || secrets.GITHUB_TOKEN }}
          label: '✅ Fixed'
